title: Sudip Adhikari
logo: /assets/profile.png
email: sudiadhikari@gmail.com
description: Machine Learning Engineer || Data Scientist || NLP || TensorFlow || Python ||Scikit-learn
favicon: false
color-scheme: light
remote_theme: saathisudip/jekyll-theme-minimalistic

google_analytics: G-0RXV630V8X

url: "https://google.com/"

plugins:
  - jekyll-seo-tag
  - jemoji
  - jekyll-sitemap

platforms:
  - name: Charlotte, NC, USA
    icon: <i class="fa-brands fa-location-dot"></i>
    link: https://github.com/saathisudip
  - name: Résumé
    icon: <i class="fa-solid fa-file-lines"></i>
    link: ./assets/resume.pdf
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/saathisudip
  - name: LinkedIn
    icon: <i class="fa-brands fa-linkedin"></i>
    link: https://www.linkedin.com/in/sudiadhikari
  - name: Projects
    icon: <i class="fa-solid fa-file-code"></i>
    link: ./projects
  - name: Certifications
    icon: <i class="fa-solid fa-award"></i>
    link: ./certifications
  - name: Open Source
    icon: <i class="fa-solid fa-ghost"></i>
    link: ./open-source
